name: Coverage

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

permissions:
  contents: read


jobs:
  coverage:
    name: Check and Upload (packages/${{ matrix.package }})
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        package:
          - builder
          - cli
          - fs
          - logger
          - project
          - server
    steps:

    - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1

    - name: Setup Node.js
      uses: actions/setup-node@820762786026740c76f36085b0efc47a31fe5020 # v7.0.0
      with:
        node-version: 22.22.2

    - name: Install dependencies
      run: npm ci

    - name: Check coverage
      working-directory: packages/${{ matrix.package }}
      run: npm run coverage

    - name: Send parallel reports to Coveralls for all packages
      uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
      continue-on-error: true # Do not fail the job if coverage reporting fails (e.g. service is down)
      with:
        parallel: true
        base-path: packages/${{ matrix.package }}
        flag-name: ${{ matrix.package }}

  finish:
    needs: coverage
    if: ${{ always() }}
    runs-on: ubuntu-24.04
    steps:
      - name: Close parallel build
        uses: coverallsapp/github-action@8d6379e14d29928660c4ba802d8e85393440b329 # v2.3.8
        with:
          parallel-finished: true
